spring:
  batch:
    jdbc:
      initialize-schema: always
batch:
  db:
    conf:
      db-url: ${BATCH_DB_URL:jdbc:mysql://localhost:3317/spring_batch}
      user: ${BATCH_DB_USER:user}
      pass: ${BATCH_DB_PASS:pass}
    source:
      conf:
        db-url: ${BATCH_SOURCE_DB_URL:jdbc:postgresql://localhost:5433/university}
        user: ${BATCH_SOURCE_DB_USER:user}
        pass: ${BATCH_SOURCE_DB_PASS:pass}
    dest:
      conf:
        db-url: ${BATCH_DEST_DB_URL:jdbc:mysql://localhost:3316/university}
        user: ${BATCH_DEST_DB_USER:user}
        pass: ${BATCH_DEST_DB_PASS:pass}