version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: batch-job-storage-db-1
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: spring_batch
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3319:3306"
    volumes:
      - mysql-spring-batch-db-2:/var/lib/mysql
  batch-job-test-1:
    image: docker-repo.localdomain/batch-postgres-mysql:0.0.1-SNAPSHOT
    container_name: exec-container-1
    environment:
      BATCH_ENABLED: true
      BATCH_DB_URL: jdbc:mysql://mysqldb:3306/spring_batch
      BATCH_SOURCE_DB_URL: jdbc:postgresql://192.168.100.166:54033/university
      BATCH_DEST_DB_URL: jdbc:mysql://192.168.100.166:33016/university
    depends_on:
      - mysqldb
volumes:
  mysql-spring-batch-db-2:
    driver: local